code/Lunchtime/Lunchtime/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import static
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name="index"),
    path("menu/", include("parsers_app.urls", namespace="restaurant"))
]


if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/Lunchtime/parsers_app/urls.py
from django.urls import path
from parsers_app.views import menu_view, manual_run

app_name = "parsers_app"

urlpatterns = [
    path("<int:restaurant_id>/", menu_view, name="menu"),
    path("manual", manual_run, name="manual_spider_run")
]

code/Lunchtime/parsers_app/models.py
from django.db import models

class Restaurants(models.Model):
    class Meta:
        verbose_name = "Ravintola"
        verbose_name_plural = "Ravintolat"
        ordering = ("name",)

    name = models.CharField(max_length=128, unique=True, verbose_name="Ravintolan nimi")
    is_active = models.BooleanField(default=True, blank=False, verbose_name="Actiivinen")
    url = models.URLField(unique=True, verbose_name="Menu url")
    map_url = models.URLField(blank=True, null=True, default=None, verbose_name="Sijainti kartaalla")
    address = models.CharField(max_length=256, blank=True, null=True, default=None, verbose_name="Osoite")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Luotu")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Päivitetty")

    def __str__(self):
        return self.name

    @property
    def to_dict(self):
        return {
            "name": self.name,
            "is_active": self.is_active,
            "url": self.url,
            "Created_at": self.created_at,
            "map_url": self.map_url,
            "address": self.address
        }

class RestaurantMenu(models.Model):
    class Meta:
        verbose_name = "Lounaslista"
        verbose_name_plural = "Lounaslistat"
        ordering = ("-id", "-added_at")

    id = models.AutoField(primary_key=True, verbose_name='id')
    restaurant = models.ForeignKey("Restaurants", related_name="restaurants", unique=False,
                           on_delete=models.CASCADE, verbose_name="Lounaspaikka")
    day = models.CharField(max_length=64, verbose_name="Päivä")
    menu_catalogs = models.CharField(max_length=128, blank=True, null=True, default=None, verbose_name="Valikon osiot")
    dishes = models.TextField(blank=True, null=True, verbose_name="Ruoka")
    dishes_description = models.TextField(blank=True, verbose_name="Kuvaus")
    price = models.CharField(max_length=64, verbose_name="Hinta",
                                null=True, blank=True, default=None)
    additional_price = models.CharField(max_length=64, verbose_name="Hinta valikoima", blank=True, null=True, default=None)
    info = models.TextField(blank=True, verbose_name="Info")
    additional_info = models.TextField(blank=True, verbose_name="Lisää info")
    date = models.DateField(blank=False, verbose_name="Päivämäärä")
    added_at = models.DateTimeField(auto_now_add=True, verbose_name='Luotu')

    def __str__(self):
        return f" {self.restaurant.name} | {self.day} | {self.date}"

    @property
    def dishes_as_list(self):
        if self.dishes:
            return list(self.dishes.split("\n"))

    @property
    def additional_info_as_list(self):
        if self.additional_info:
            return list(self.additional_info.split("\n"))

    @property
    def to_dict(self):
        return {
            "restaurant": self.restaurant.name,
            "day": self.day,
            "menu_catalogs": self.menu_catalogs,
            "dishes": self.dishes,
            "dishes_description": self.dishes_description,
            "price": self.price,
            "additional_price": self.additional_price,
            "info": self.info,
            "additional_info": self.additional_info,
            "date": self.date
        }


class Errors(models.Model):
    class Meta:
        verbose_name = "Error "
        verbose_name_plural = "Errors"
        ordering = ("-target",)

    id = models.AutoField(primary_key=True)
    target = models.ForeignKey("Restaurants", on_delete=models.CASCADE, verbose_name="Virheen kohde")
    resolved = models.BooleanField(default=False, verbose_name="Korjattu")
    error_text = models.TextField(blank=False, verbose_name="Virheen kuvaus")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Päivä ja aika")

    def __str__(self):
        return f"{self.target.name} | {self.created_at}"

code/Lunchtime/users/models.py
from django.db import models

# Create your models here.

code/Lunchtime/Lunchtime/views.py
from django.shortcuts import render
from parsers_app.models import Restaurants

def index(request):
    content = {"restaurants": Restaurants.objects.all()}
    return render(request, "index.html", context=content)

code/Lunchtime/parsers_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Restaurants, RestaurantMenu
from datetime import date
from .tasks import run_scrapy_task

today = date.today()

def manual_run(request):
    run_scrapy_task.delay()
    return HttpResponseRedirect("/")

def menu_view(request, restaurant_id):
    content = {
        "restaurants": Restaurants.objects.all(),
        "menu": RestaurantMenu.objects.filter(restaurant=restaurant_id, date=today).first()
    }
    return render(request, "menu.html", context=content)


code/Lunchtime/users/views.py
from django.shortcuts import render

# Create your views here.

code/Lunchtime/parsers_app/templates/menu.html
{% extends "index.html" %}

{% block body %}
<section class="container menu" >
	<div class="menu-block" id="{{menu.restaurant.name}}">
		<p><strong>Today is {% now "l"%}</strong></p>
		{% if menu.dishes_as_list %}
		<div class="dish">
			<p><strong>Main menu:</strong></p>
			{% for dish in menu.dishes_as_list %}
			<p><span> {{ dish }}</span></p>
			{% endfor %}
			<p><strong> Lunch price {{ menu.price }}</strong></p>
		</div>
		{% else%}
		<div> <b> Sorry. menu is not available for today.</b></div>
		{% endif %}
		<div class="info">
			{% for info in menu.additional_info_as_list %}
			<p><span>{{ info }}</span></p>
			{% endfor %}
		</div>
	</div>
</div>
</section>
{% endblock %}

code/Lunchtime/templates/base.html
{% block head %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
	      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="shortcut icon" href="https://www.google.com/s2/u/0/favicons?domain=etteplan.com" type="image/x-icon">
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css">
	<meta charset="UTF-8">
	<title>Lunch time</title>
</head>

{% endblock %}

<body>
{% include "includes/navigation.html" %}
{% block body %}

{% endblock %}
</body>
{% block footer %}
<footer>
	<div>
		Today is {% now "l d-m-Y  h:i a " %}
	</div>
</footer>
{% endblock %}
</html>

code/Lunchtime/templates/includes/maps.html
<script src='https://oskari.org/js/rpc/rpc-client.min.js'></script>
<script>
 window.onload = function() {
    let iframes = document.getElementsByTagName("iframe")
	for (let i = 0; i < iframes.length; i++) {
		let regularExpression = /(-\s?\d+\s?(\w+)?)/
		let place = {
			address: iframes[i].getAttribute("data-address").replace(regularExpression, ""),
			id: iframes[i].getAttribute("id"),
			marker_id: iframes[i].getAttribute("data-id")
		}
		//console.log(place)

		let IFRAME_DOMAIN = 'https://kartta.paikkatietoikkuna.fi';
	    let iFrame = document.getElementById(place["id"]);
	    let channel = OskariRPC.connect(
	        iFrame,
	        IFRAME_DOMAIN
	    );
	    channel.onReady(function() {
	        //channel is now ready and listening.
	        channel.log('Map is now listening');
	    });
	    channel.postRequest('SearchRequest', [place["address"]]);
	    let zoomOut = 9 // adjust 1-13
	    channel.handleEvent("SearchResultEvent", function(data) {
	        let marker = {
	            x:data.result.locations[0].lon,
	            y:data.result.locations[0].lat,
	            color: 'ff0000',
	            msg : place["id"],
	            shape: 3, // icon number (0-6)
	            size: 3
	        }
	      channel.postRequest('MapModulePlugin.AddMarkerRequest', [marker, place["marker_id"]]);
	      channel.postRequest("MapMoveRequest", [marker.x, marker.y, zoomOut ])
	    })
	}
 }
</script>

code/Lunchtime/templates/includes/navigation.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" id="navbar-brand" href="/" title="To mainpage">LunchTime</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        {% for restaurant in restaurants%}
          {% if restaurant.is_active %}
        <li class="nav-item"
          {% if request.resolver_match.kwargs.restaurant_id == restaurant.id %}
              title="current: {{restaurant.name}}"
          {% endif %}>
          <strong>
            <a class="nav-link"
               {% if request.resolver_match.kwargs.restaurant_id == restaurant.id %}
                  id="active"
               {% endif %}
               href="{% url 'restaurant:menu' restaurant.id %}">
              {{ restaurant.name|title }}
            </a>
          </strong>
        </li>
          {% endif %}
		{% endfor %}

      </ul>
    </div>
  </div>
</nav>

code/Lunchtime/templates/index.html
{% extends "base.html" %}

{% block body %}
<section class="container">
	{% for restaurant in restaurants %}
		{% if restaurant.is_active %}
		<div class="restaurant-container">
			<div class="main-info">
				<a class="restaurant" href="{% url 'restaurant:menu' restaurant.id %}">
					<h4> {{ restaurant.name }} </h4>
				</a>
				<p>{{ restaurant.address|title }}</p>
				<a href="{{ restaurant.url }}" target="_blank" title="Direct link to restaurant">
					Direct link to restaurant
					<i class="fas fa-arrow-right"></i>
				</a>
			</div>
			{% if restaurant.address %}
			<iframe src="https://kartta.paikkatietoikkuna.fi/published/fi/19532910-5a95-454e-a8c6-aa569f127a16"
	            allow="geolocation" style="border: none; width: 600px; height: 200px;" id="{{restaurant.name}}"
				data-address="{{restaurant.address}}" data-id="{{restaurant.pk}}"></iframe>
			{% endif %}
		</div>
		{% endif %}
	{% endfor %}
	{% if restaurants %}
		{% include "includes/maps.html" %}
	{% endif %}
</section>
{% endblock %}
